version: "3.1"

services:
  mysql:
    image: mysql:8.0.33
    container_name: dundee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123 # 👈 use this to eliminate any weirdness
      MYSQL_DATABASE: DUNDEEDAILYDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

volumes:
  mysql_data:
